# Generated by Django 2.2.28 on 2022-09-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirect',
            options={'ordering': ['-created_at'], 'verbose_name': 'Redirect', 'verbose_name_plural': 'Redirects'},
        ),
    ]
